security:
    # encoders n'est plus utilisé dans les versions plus récentes de Symfony; Symfony configure les encodeurs automatiquement selon le type de mot de passe.
    password_hashers:
        App\Entity\Pharmacie:
            algorithm: auto

    providers:
        # Configuration du fournisseur d'utilisateurs pour charger les pharmaciens depuis la base de données
        pharmacie_provider:
            entity:
                class: App\Entity\Pharmacie
                property: email # L'attribut utilisé pour l'identification, ici l'email

    firewalls:
        # Permet l'accès public à certaines routes
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # Définition du firewall pour les utilisateurs authentifiés
        main:
            #anonymous: lazy
            provider: pharmacie_provider
            # Le chemin où rediriger après un succès de connexion
            form_login:
                login_path: login
                check_path: login
                default_target_path: pharmacie_dashboard # Le chemin où rediriger après une connexion réussie
            logout:
                path: app_logout
                target: login # Le chemin où rediriger après la déconnexion
                invalidate_session: true
            # Paramètres des cookies sécurisés
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800 # 1 semaine en secondes
                path: /
                httponly: true

    access_control:
        # Autoriser l'accès à la page de connexion pour tous
        - { path: ^/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        # Autoriser l'accès à certaines pages publiques
        - { path: ^/public, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        # Protéger l'accès à l'administration des pharmaciens
        - { path: ^/admine, roles: ROLE_PHARMACIEN }
